/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author andr6491
 */
public class AndrewTest extends javax.swing.JFrame {

    /**
     * Creates new form AndrewTest
     */
    String[][] movies;

    public AndrewTest() {
        initComponents();
        movies = fillData();
    }

    public String[][] fillData() {

        String data[][] = new String[][]{
            {"Galaxy-10 pm", "Life of Pi"},
            {"Galaxy-7 pm", "GI Joe"},
            {"Galaxy-10 pm", "The Host"},
            {"Galaxy-7 pm", "GI Joe"},
            {"Galaxy-8 pm", "GI Joe"},
            {"Uptown-5 pm", "Oblivion"},
            {"Galaxy-9 pm", "The Host"},
            {"Bayfield-8 pm", "Life of Pi"},
            {"Galaxy-1 pm", "The Host"},
            {"Galaxy-3 pm", "Silver Lining"},
            {"Bayfield-5 pm", "GI Joe"},
            {"Uptown-6 pm", "The Host"},
            {"Galaxy-7 pm", "The Host"},
            {"Galaxy-5 pm", "Life of Pi"},
            {"Uptown-4 pm", "Silver Lining"},
            {"Bayfield-7 pm", "GI Joe"},
            {"Bayfield-2 pm", "GI Joe"},
            {"Galaxy-4 pm", "Life of Pi"},
            {"Uptown-10 pm", "Life of Pi"},
            {"Galaxy-1 pm", "Identity Theif"},
            {"Bayfield-5 pm", "The Host"},
            {"Galaxy-6 pm", "Oblivion"},
            {"Bayfield-10 pm", "GI Joe"},
            {"Uptown-5 pm", "Identity Theif"},
            {"Uptown-3 pm", "Life of Pi"},
            {"Uptown-7 pm", "The Host"},
            {"Galaxy-2 pm", "The Host"},
            {"Galaxy-9 pm", "GI Joe"},
            {"Galaxy-8 pm", "The Host"},
            {"Uptown-4 pm", "Silver Lining"},
            {"Galaxy-5 pm", "Silver Lining"},
            {"Bayfield-8 pm", "The Host"},
            {"Galaxy-1 pm", "The Host"},
            {"Uptown-1 pm", "The Host"},
            {"Uptown-4 pm", "Life of Pi"},
            {"Galaxy-4 pm", "The Host"},
            {"Uptown-1 pm", "Oblivion"},
            {"Galaxy-6 pm", "Life of Pi"},
            {"Bayfield-2 pm", "Oblivion"},
            {"Galaxy-6 pm", "Silver Lining"},
            {"Uptown-6 pm", "GI Joe"},
            {"Galaxy-2 pm", "The Host"},
            {"Uptown-5 pm", "GI Joe"},
            {"Bayfield-9 pm", "The Host"},
            {"Bayfield-5 pm", "The Host"},
            {"Bayfield-1 pm", "Identity Theif"},
            {"Bayfield-2 pm", "GI Joe"},
            {"Uptown-1 pm", "GI Joe"},
            {"Uptown-10 pm", "GI Joe"},
            {"Uptown-5 pm", "The Host"}
        };

        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Time!");
        setResizable(false);

        jLabel1.setText("Movie title:");

        txtOut.setColumns(20);
        txtOut.setRows(5);
        jScrollPane1.setViewportView(txtOut);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //Start by clearing out the text area
        txtOut.setText("");
        //Iterate over the array and append each movie time
        for (String m: getTimes(txtTitle.getText())){
            txtOut.append(m+"\n");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //Clear out all text
        txtOut.setText("");
        txtTitle.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private String[] getTimes(String name) {
        short count = 0;
        //Determine length of string array to return
        for (String n[] : movies) {
            if (name.equalsIgnoreCase(n[1])) {
                count++;
            }
        }
        
        //If the movie is not found, don't bother with the rest
        //Return an error
        if (count ==0){
            String msg[] = {"Error!","Movie not found"};
            return msg ;
        
        }
        //Create string array
        String list[] = new String[count];
        count = 0;
        //Iterate over the array
        for (String[] movie : movies) {
            if (movie[1].equalsIgnoreCase(name)) {
                //Add the time
                list[count] = movie[0];
                count++;
            }
        }
        return list;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndrewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndrewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndrewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndrewTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndrewTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtOut;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
